### PR TITLE
added NL as country option

### PR DESCRIPTION
**Pull request by TerrorSource**
added NL as country option for 1.70
It now creates an URL which works for NL users.

### CODE REVIEW

**Review by SquidBytes — CHANGES_REQUESTED** [review]
Im on mobile so it's a bit tricky to really see, but based on the commit it seems like the only thing that would be changing is the addition if Netherlands.
However, it's showing as every line being changed.
Is there a way you can verify your code settings so every line isn't new. Like if your like endings are different, or a plugin altered the spaces.
Unless that is all new lol

**Comment by TerrorSource** [comment]
> Im on mobile so it's a bit tricky to really see, but based on the commit it seems like the only thing that would be changing is the addition if Netherlands. However, it's showing as every line being changed. Is there a way you can verify your code settings so every line isn't new. Like if your like endings are different, or a plugin altered the spaces. Unless that is all new lol

I tried to edit the 2 files but i had to make 2 PRs then, im not that familiar with Github ;)

Ive downloaded the files and re-uploaded them in my fork, thats why it shows that all lines are new.

**Comment by TerrorSource** [comment]
const.py edits:
REGION_OPTIONS = ["Netherlands", "UK&Europe", "Australia", "North America & Canada"]
REGIONS = {
    "Netherlands": {
        "region": "1E8C7794-FF5F-49BC-9596-A1E0C86C5B19",
        "locale": "nl-NL",
        "locale_short": "NL", #Temp fix 
        "locale_url": "https://login.ford.nl"
        
fordpass_new.py edits:
region_lookup = {
    "Netherlands": "1E8C7794-FF5F-49BC-9596-A1E0C86C5B19",
            elif self.region2 == "Netherlands":
            countryheader = "NLD"

**Comment by TheLizard** [comment]
As I have recently bought a new car, I got interested in this plugin, checking this pull request I noticed the files are marked as added because they are added to the root directory, not inside the custom_components/fordpass directory.

**Comment by TheLizard** [comment]
I have created a new pull request, to be able to get this change in

**Comment by SquidBytes** [comment]
#517

**Pull request closed without merging**
