### PR TITLE
Added charge_logs function to return the charge logs

### PR DESCRIPTION
**Pull request by SquidBytes**
This is my first time using github and I've never worked with other public branches

I've also never worked on a home assistant integration, so I figured I would try to add the feature request I asked for or what I can add. 
I added a function for charge_logs / charge_data, and it will return valuable data but I didn't know how to properly integrate it into hass

Figured I would make a PR

### CODE REVIEW

**Comment by itchannel** [comment]
Can you provide me with a copy of the json that is returned from your function as I don't have access to charge logs on my vehicle. I noticed in your issue you attached a couple of json files. Is one of those returned from this function?

**Comment by SquidBytes** [comment]
Yeah, this function will return all the charge logs.
The charge logs are then displayed by id
The 2 .json files I attached in the request are what is returned.

Let me know how else I can help

**Comment by SquidBytes** [comment]
Ended up working on this some more.
I think I was able to do the proper way to implement it into HomeAssistant.
I'm still not doing anything with charge_logs, but I added a new function that returns the charge status.
I created a new sensor in HomeAssistant that reports the status of that API query.

If you're curious, this is the data that is returned (some items removed for privacy)
I tested this with my Lightning, charging slowly at Home - but it should work with different charge types

`{"deviceId":"<vin>","chargerType":"AC_BASIC","currentTargetSoc":100,"plugDetails":{"plugInTime":"2023-10-04T23:51:25Z","totalPluggedInTime":669,"plugInDte":225.2,"totalDistanceAdded":0.0},"power":1084.8,"location":{"id":2,"type":"SAVED","name":"<saved-name>","address":{"address1":"<steet>","city":"<city>","state":"<state>","country":"USA","postalCode":"<postal>"},"geoHash":"<geohash>","latitude":11.111111,"longitude":-11.111111,"timeZoneOffset":"UTC-04:00","network":"UNKNOWN"},"chargeProfile":{"chargeMode":"CHARGE_NOW","targetSoc":90,"schedules":[{"days":"WEEKDAY","windows":[{"startTime":"00:00","endTime":"00:00"}]},{"days":"WEEKEND","windows":[{"startTime":"00:00","endTime":"00:00"}]}]},"energyConsumed":194.91}`

Here is a screenshot of it in HomeAssistant
image

**Comment by skai21** [comment]
Did this find it's way into the production version somehow?
I would really love to have this, and currently don't see the sensors appearing.

Thanks in advance!

**Comment by SquidBytes** [comment]
Which feature are you looking for? Charge logs are not in this integration, but I do have my own person project around obtaining your charge logs.

The ability to start, and stop charging is currently in progress of being supported. I just haven't had much time to debug and implement it.

**Pull request closed without merging**
